export const LOGOUT_SYSTEM = "LOGOUT_SYSTEM";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FALSE = "LOGIN_FALSE";

export const AUTH = "AUTH";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FALSE = "AUTH_FALSE";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FALSE = "REGISTER_FALSE";

export const ACTIVE_ACCOUNT = "ACTIVE_ACCOUNT";
export const ACTIVE_ACCOUNT_SUCCESS = "ACTIVE_ACCOUNT_SUCCESS";
export const ACTIVE_ACCOUNT_FALSE = "ACTIVE_ACCOUNT_FALSE";


