//AUTH
export const LOGOUT_SYSTEM = "LOGOUT_SYSTEM";

export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FALSE = "LOGIN_FALSE";

export const AUTH = "AUTH";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FALSE = "AUTH_FALSE";

export const REGISTER = "REGISTER";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FALSE = "REGISTER_FALSE";

export const ACTIVE_ACCOUNT = "ACTIVE_ACCOUNT";
export const ACTIVE_ACCOUNT_SUCCESS = "ACTIVE_ACCOUNT_SUCCESS";
export const ACTIVE_ACCOUNT_FALSE = "ACTIVE_ACCOUNT_FALSE";

export const CHECK_ACCOUNT_EXISTS = "CHECK_ACCOUNT_EXISTS";
export const CHECK_ACCOUNT_EXISTS_SUCCESS = "CHECK_ACCOUNT_EXISTS_SUCCESS";
export const CHECK_ACCOUNT_EXISTS_FALSE = "CHECK_ACCOUNT_EXISTS_FALSE";

//TASK
export const ADD_TASK = "ADD_TASK";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_FALSE = "ADD_TASK_FALSE"; 

export const GET_TASK_BY_ID = "GET_TASK_BY_ID";
export const GET_TASK_BY_ID_SUCCESS = "GET_TASK_BY_ID_SUCCESS";
export const GET_TASK_BY_ID_FALSE = "GET_TASK_BY_ID_FALSE"; 

//GOAL
export const GET_GOAL = "GET_GOAL";
export const GET_GOAL_SUCCESS = "GET_GOAL_SUCCESS";
export const GET_GOAL_FALSE = "GET_GOAL_FALSE"; 

export const ADD_GOAL = "ADD_GOAL";
export const ADD_GOAL_SUCCESS = "ADD_GOAL_SUCCESS";
export const ADD_GOAL_FALSE = "ADD_GOAL_FALSE"; 


export const RESET = "RESET";